// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class ReqHead;
@class ReqHead_Builder;
@class RspHead;
@class RspHead_Builder;
@class UserBaseInfo;
@class UserBaseInfo_Builder;

@interface BaseRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ReqHead : PBGeneratedMessage {
@private
  BOOL hasUid_:1;
  BOOL hasSkey_:1;
  BOOL hasCommand_:1;
  BOOL hasBody_:1;
  BOOL hasCTs_:1;
  BOOL hasPlatform_:1;
  NSString* uid;
  NSString* skey;
  NSString* command;
  NSData* body;
  int32_t cTs;
  int32_t platform;
}
- (BOOL) hasUid;
- (BOOL) hasSkey;
- (BOOL) hasCommand;
- (BOOL) hasBody;
- (BOOL) hasCTs;
- (BOOL) hasPlatform;
@property (readonly, retain) NSString* uid;
@property (readonly, retain) NSString* skey;
@property (readonly, retain) NSString* command;
@property (readonly, retain) NSData* body;
@property (readonly) int32_t cTs;
@property (readonly) int32_t platform;

+ (ReqHead*) defaultInstance;
- (ReqHead*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ReqHead_Builder*) builder;
+ (ReqHead_Builder*) builder;
+ (ReqHead_Builder*) builderWithPrototype:(ReqHead*) prototype;

+ (ReqHead*) parseFromData:(NSData*) data;
+ (ReqHead*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReqHead*) parseFromInputStream:(NSInputStream*) input;
+ (ReqHead*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (ReqHead*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ReqHead*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ReqHead*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ReqHead_Builder : PBGeneratedMessage_Builder {
@private
  ReqHead* result;
}

- (ReqHead*) defaultInstance;

- (ReqHead_Builder*) clear;
- (ReqHead_Builder*) clone;

- (ReqHead*) build;
- (ReqHead*) buildPartial;

- (ReqHead_Builder*) mergeFrom:(ReqHead*) other;
- (ReqHead_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ReqHead_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasUid;
- (NSString*) uid;
- (ReqHead_Builder*) setUid:(NSString*) value;
- (ReqHead_Builder*) clearUid;

- (BOOL) hasSkey;
- (NSString*) skey;
- (ReqHead_Builder*) setSkey:(NSString*) value;
- (ReqHead_Builder*) clearSkey;

- (BOOL) hasCommand;
- (NSString*) command;
- (ReqHead_Builder*) setCommand:(NSString*) value;
- (ReqHead_Builder*) clearCommand;

- (BOOL) hasBody;
- (NSData*) body;
- (ReqHead_Builder*) setBody:(NSData*) value;
- (ReqHead_Builder*) clearBody;

- (BOOL) hasCTs;
- (int32_t) cTs;
- (ReqHead_Builder*) setCTs:(int32_t) value;
- (ReqHead_Builder*) clearCTs;

- (BOOL) hasPlatform;
- (int32_t) platform;
- (ReqHead_Builder*) setPlatform:(int32_t) value;
- (ReqHead_Builder*) clearPlatform;
@end

@interface RspHead : PBGeneratedMessage {
@private
  BOOL hasSkey_:1;
  BOOL hasSTs_:1;
  BOOL hasCommand_:1;
  BOOL hasContent_:1;
  BOOL hasRetcode_:1;
  NSString* skey;
  NSString* sTs;
  NSString* command;
  NSData* content;
  int32_t retcode;
}
- (BOOL) hasSkey;
- (BOOL) hasSTs;
- (BOOL) hasCommand;
- (BOOL) hasRetcode;
- (BOOL) hasContent;
@property (readonly, retain) NSString* skey;
@property (readonly, retain) NSString* sTs;
@property (readonly, retain) NSString* command;
@property (readonly) int32_t retcode;
@property (readonly, retain) NSData* content;

+ (RspHead*) defaultInstance;
- (RspHead*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RspHead_Builder*) builder;
+ (RspHead_Builder*) builder;
+ (RspHead_Builder*) builderWithPrototype:(RspHead*) prototype;

+ (RspHead*) parseFromData:(NSData*) data;
+ (RspHead*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RspHead*) parseFromInputStream:(NSInputStream*) input;
+ (RspHead*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (RspHead*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RspHead*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RspHead*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RspHead_Builder : PBGeneratedMessage_Builder {
@private
  RspHead* result;
}

- (RspHead*) defaultInstance;

- (RspHead_Builder*) clear;
- (RspHead_Builder*) clone;

- (RspHead*) build;
- (RspHead*) buildPartial;

- (RspHead_Builder*) mergeFrom:(RspHead*) other;
- (RspHead_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RspHead_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSkey;
- (NSString*) skey;
- (RspHead_Builder*) setSkey:(NSString*) value;
- (RspHead_Builder*) clearSkey;

- (BOOL) hasSTs;
- (NSString*) sTs;
- (RspHead_Builder*) setSTs:(NSString*) value;
- (RspHead_Builder*) clearSTs;

- (BOOL) hasCommand;
- (NSString*) command;
- (RspHead_Builder*) setCommand:(NSString*) value;
- (RspHead_Builder*) clearCommand;

- (BOOL) hasRetcode;
- (int32_t) retcode;
- (RspHead_Builder*) setRetcode:(int32_t) value;
- (RspHead_Builder*) clearRetcode;

- (BOOL) hasContent;
- (NSData*) content;
- (RspHead_Builder*) setContent:(NSData*) value;
- (RspHead_Builder*) clearContent;
@end

@interface UserBaseInfo : PBGeneratedMessage {
@private
  BOOL hasNick_:1;
  BOOL hasIconUrl_:1;
  BOOL hasLoginskey_:1;
  BOOL hasLogintime_:1;
  BOOL hasEmail_:1;
  BOOL hasMobileno_:1;
  BOOL hasOpenid_:1;
  BOOL hasProv_:1;
  BOOL hasCity_:1;
  BOOL hasZone_:1;
  BOOL hasIshow_:1;
  BOOL hasAvg_:1;
  BOOL hasSex_:1;
  BOOL hasFrom_:1;
  NSString* nick;
  NSString* iconUrl;
  NSString* loginskey;
  NSString* logintime;
  NSString* email;
  NSString* mobileno;
  NSString* openid;
  NSString* prov;
  NSString* city;
  NSString* zone;
  NSString* ishow;
  int32_t avg;
  int32_t sex;
  int32_t from;
}
- (BOOL) hasAvg;
- (BOOL) hasSex;
- (BOOL) hasNick;
- (BOOL) hasIconUrl;
- (BOOL) hasLoginskey;
- (BOOL) hasLogintime;
- (BOOL) hasEmail;
- (BOOL) hasMobileno;
- (BOOL) hasOpenid;
- (BOOL) hasFrom;
- (BOOL) hasProv;
- (BOOL) hasCity;
- (BOOL) hasZone;
- (BOOL) hasIshow;
@property (readonly) int32_t avg;
@property (readonly) int32_t sex;
@property (readonly, retain) NSString* nick;
@property (readonly, retain) NSString* iconUrl;
@property (readonly, retain) NSString* loginskey;
@property (readonly, retain) NSString* logintime;
@property (readonly, retain) NSString* email;
@property (readonly, retain) NSString* mobileno;
@property (readonly, retain) NSString* openid;
@property (readonly) int32_t from;
@property (readonly, retain) NSString* prov;
@property (readonly, retain) NSString* city;
@property (readonly, retain) NSString* zone;
@property (readonly, retain) NSString* ishow;

+ (UserBaseInfo*) defaultInstance;
- (UserBaseInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserBaseInfo_Builder*) builder;
+ (UserBaseInfo_Builder*) builder;
+ (UserBaseInfo_Builder*) builderWithPrototype:(UserBaseInfo*) prototype;

+ (UserBaseInfo*) parseFromData:(NSData*) data;
+ (UserBaseInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserBaseInfo*) parseFromInputStream:(NSInputStream*) input;
+ (UserBaseInfo*) parseDelimitedFromInputStream:(NSInputStream*) input;
+ (UserBaseInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserBaseInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserBaseInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserBaseInfo_Builder : PBGeneratedMessage_Builder {
@private
  UserBaseInfo* result;
}

- (UserBaseInfo*) defaultInstance;

- (UserBaseInfo_Builder*) clear;
- (UserBaseInfo_Builder*) clone;

- (UserBaseInfo*) build;
- (UserBaseInfo*) buildPartial;

- (UserBaseInfo_Builder*) mergeFrom:(UserBaseInfo*) other;
- (UserBaseInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserBaseInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAvg;
- (int32_t) avg;
- (UserBaseInfo_Builder*) setAvg:(int32_t) value;
- (UserBaseInfo_Builder*) clearAvg;

- (BOOL) hasSex;
- (int32_t) sex;
- (UserBaseInfo_Builder*) setSex:(int32_t) value;
- (UserBaseInfo_Builder*) clearSex;

- (BOOL) hasNick;
- (NSString*) nick;
- (UserBaseInfo_Builder*) setNick:(NSString*) value;
- (UserBaseInfo_Builder*) clearNick;

- (BOOL) hasIconUrl;
- (NSString*) iconUrl;
- (UserBaseInfo_Builder*) setIconUrl:(NSString*) value;
- (UserBaseInfo_Builder*) clearIconUrl;

- (BOOL) hasLoginskey;
- (NSString*) loginskey;
- (UserBaseInfo_Builder*) setLoginskey:(NSString*) value;
- (UserBaseInfo_Builder*) clearLoginskey;

- (BOOL) hasLogintime;
- (NSString*) logintime;
- (UserBaseInfo_Builder*) setLogintime:(NSString*) value;
- (UserBaseInfo_Builder*) clearLogintime;

- (BOOL) hasEmail;
- (NSString*) email;
- (UserBaseInfo_Builder*) setEmail:(NSString*) value;
- (UserBaseInfo_Builder*) clearEmail;

- (BOOL) hasMobileno;
- (NSString*) mobileno;
- (UserBaseInfo_Builder*) setMobileno:(NSString*) value;
- (UserBaseInfo_Builder*) clearMobileno;

- (BOOL) hasOpenid;
- (NSString*) openid;
- (UserBaseInfo_Builder*) setOpenid:(NSString*) value;
- (UserBaseInfo_Builder*) clearOpenid;

- (BOOL) hasFrom;
- (int32_t) from;
- (UserBaseInfo_Builder*) setFrom:(int32_t) value;
- (UserBaseInfo_Builder*) clearFrom;

- (BOOL) hasProv;
- (NSString*) prov;
- (UserBaseInfo_Builder*) setProv:(NSString*) value;
- (UserBaseInfo_Builder*) clearProv;

- (BOOL) hasCity;
- (NSString*) city;
- (UserBaseInfo_Builder*) setCity:(NSString*) value;
- (UserBaseInfo_Builder*) clearCity;

- (BOOL) hasZone;
- (NSString*) zone;
- (UserBaseInfo_Builder*) setZone:(NSString*) value;
- (UserBaseInfo_Builder*) clearZone;

- (BOOL) hasIshow;
- (NSString*) ishow;
- (UserBaseInfo_Builder*) setIshow:(NSString*) value;
- (UserBaseInfo_Builder*) clearIshow;
@end

